### ISSUE TITLE
Run for specific subscription

### ISSUE THREAD

**Issue by mdaslamansari** [cyberark/BlobHunter#10]
May i request new feature to allow selecting the specific subscription or excluding some subscription from the same.

We have one of the subscription where a storage account has lots of containers and because of it the script is getting timed-out. We want to exclude that subscription from the scans.

**Comment by rsvirk** [comment]
You can amend it like this:   Just change MYSUBSCRIPTION to the one you want to scan
for i in range(0, len(subs_ids)):
        #check_subscription(tenants_ids[i], tenants_names[i], subs_ids[i], subs_names[i], credentials)
        if subs_names[i] == 'MYSUBSCRIPTION':
            print(subs_names[i])
            check_subscription(tenants_ids[i], tenants_names[i], subs_ids[i], subs_names[i], credentials)
            print("\n[+] Checked that sub above", flush=True)
