### ISSUE TITLE
ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by seakish** [cyberark/BlobHunter#3]
Getting the error below. Have the Azure CLI and Python 3.8 64 bit installed from Python.Org on Windows 10. 

What am I doing wrong? Thanks! 

C:\BlobHunter-main\BlobHunter-main>python Blobhunter.py
Traceback (most recent call last):
  File "Blobhunter.py", line 1, in <module>
    import azure.core.exceptions
ModuleNotFoundError: No module named 'azure'

C:\BlobHunter-main\BlobHunter-main>

**Comment by DanielNiv** [comment]
Did you install the requirements.txt packages?

**Comment by seakish** [comment]
Thank you Daniel. I reinstalled and everything worked. Thanks again!
