### ISSUE TITLE
Throttling Limits

### ISSUE THREAD

**Issue by windic** [cyberark/BlobHunter#7]
## Summary
After some testing, we can see that it is not intended for users who have access to large subscriptions. In Azure Subscriptions where there are many Storage Accounts, a throtelling error occurs due to the number of requests to the Azure API.

It could be interesting if the script controls the number of requests per second in order to avoid the throtelling error. Another option could be the possibility to choose between subscription or resource group.

## Steps to Reproduce
A Simple ejecution after az login.

![Error_Blobhunter](https://user-images.githubusercontent.com/37453762/108824430-fe44ed00-75c1-11eb-8db7-0031f94c0d3f.png)

**Comment by mdaslamansari** [comment]
I am getting azure.core.exceptions.ServiceRequestError: (<urllib3.connection.HTTPSConnection object at 0x7f51db93aef0>, 'Connection to xxx.blob.core.windows.net timed out. (connect timeout=20)')

**Comment by yanivyakobovich** [comment]
Resolved.
